# Generated by Django 3.2.9 on 2021-11-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(db_index=True)),
                ('description', models.TextField(db_index=True)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('url_thumbnail', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel_id', models.TextField(default='')),
                ('channel_title', models.TextField(default='')),
            ],
        ),
    ]
